### ISSUE TITLE
Cannot remove using UI

### ISSUE THREAD

**Issue by rbellamy** [ystkme/count-word#3]
```
Uninstalling “count-word” failed.Hide output…
Failed to delete count-word: Does not exist
```

Yet it clearly does exist.

**Comment by cattaka** [comment]
I had the same issue.

**Comment by yo7** [comment]
Well.. I don't see if that is the package's problem or Atom editor's problem. Did you try not only uninstalling it from UI but also removing package files or anything like that? I can't tell the right solution because I don't use Atom anymore.
